services:
  ep_redis_users:
    image: redis:latest
    container_name: ep_redis_users
    ports:
      - "5555:6379"
    volumes:
      - ./data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    networks:
      - ep-network

  ep_postgres:
    container_name: ep_pg_sql
    image: postgres:latest
    environment:
      POSTGRES_USER: eplatform
      POSTGRES_PASSWORD: eplatform
      POSTGRES_DB: eplatform
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ep-network
    restart: unless-stopped

networks:
  ep-network:
    driver: bridge


volumes:
  postgres: